---
- name: Install vscode
  hosts: workstation
  remote_user: root
  vars_files:
    - vars/install.yml
  roles:
    - marcusburghardt.vscode

- name: Configure extensions
  hosts: workstation
  vars_files:
    - vars/configure.yml
  roles:
    - marcusburghardt.vscode
